version: '3.9'
services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
    - ./frontend:/usr/src/app
    command: sh -c "cd kid-games && npm run dev -- --port 8080 --host"
    ports:
    - "8080:8080"
